export const TOKENS = {
  LoginUseCase: Symbol.for("LoginUseCase"),
  LogoutUseCase: Symbol.for("LogoutUseCase"),
  AuthController: Symbol.for("AuthController"),
  MenuRepository: Symbol.for("MenuRepository"),
  GetMenusUseCase: Symbol.for("GetMenusUseCase"),
  GetMenuByIdUseCase: Symbol.for("GetMenuByIdUseCase"),
  CreateMenuUseCase: Symbol.for("CreateMenuUseCase"),
  UpdateMenuUseCase: Symbol.for("UpdateMenuUseCase"),
  DeleteMenuUseCase: Symbol.for("DeleteMenuUseCase"),
  MenuPublicApi: Symbol.for("MenuPublicApi"),
  TransaksiRepository: Symbol.for("TransaksiRepository"),
  CreateTransaksiUseCase: Symbol.for("CreateTransaksiUseCase"),
  GetSemuaTransaksiUseCase: Symbol.for("GetSemuaTransaksiUseCase"),
  GetDetailTransaksiUseCase: Symbol.for("GetDetailTransaksiUseCase"),
  DashboardRepository: Symbol.for("DashboardRepository"),
  GetDashboardSummaryUseCase: Symbol.for("GetDashboardSummaryUseCase"),
};
